export const languages = [
  { name: "English" },
  { name: "Mandarin Chinese" },
  { name: "Spanish" },
  { name: "Hindi" },
  { name: "French" },
  { name: "Standard Arabic" },
  { name: "Bengali" },
  { name: "Russian" },
  { name: "Portuguese" },
  { name: "Urdu" },
  { name: "Indonesian" },
  { name: "German" },
  { name: "Japanese" },
  { name: "Swahili" },
  { name: "Marathi" },
  { name: "Telugu" },
  { name: "Turkish" },
  { name: "Tamil" },
  { name: "Vietnamese" },
  { name: "Korean" },
];

export const genres = [
  { name: "Fiction" },
  { name: "Mystery" },
  { name: "Thriller" },
  { name: "Romance" },
  { name: "Science Fiction" },
  { name: "Fantasy" },
  { name: "Historical Fiction" },
  { name: "Horror" },
  { name: "Crime" },
  { name: "Adventure" },
  { name: "Young Adult" },
  { name: "Non-fiction" },
  { name: "Biography/Autobiography" },
  { name: "Memoir" },
  { name: "Self-help" },
  { name: "Business/Finance" },
  { name: "Science/Technology" },
  { name: "Travel" },
  { name: "Poetry" },
  { name: "Graphic Novel/Comic" },
];
