export const languages = [
  { name: "English" },
  { name: "Mandarin Chinese" },
  { name: "Spanish" },
  { name: "Hindi" },
  { name: "French" },
  { name: "Standard Arabic" },
  { name: "Bengali" },
  { name: "Russian" },
  { name: "Portuguese" },
  { name: "Urdu" },
  { name: "Indonesian" },
  { name: "German" },
  { name: "Japanese" },
  { name: "Swahili" },
  { name: "Marathi" },
  { name: "Telugu" },
  { name: "Turkish" },
  { name: "Tamil" },
  { name: "Vietnamese" },
  { name: "Korean" },
];

export const genres = [
  { name: "Fiction" },
  { name: "Mystery" },
  { name: "Thriller" },
  { name: "Romance" },
  { name: "Science Fiction" },
  { name: "Fantasy" },
  { name: "Historical Fiction" },
  { name: "Horror" },
  { name: "Crime" },
  { name: "Adventure" },
  { name: "Young Adult" },
  { name: "Non-fiction" },
  { name: "Biography/Autobiography" },
  { name: "Memoir" },
  { name: "Self-help" },
  { name: "Business/Finance" },
  { name: "Science/Technology" },
  { name: "Travel" },
  { name: "Poetry" },
  { name: "Graphic Novel/Comic" },
];

export const languageList = [
  "English",
  "Mandarin Chinese",
  "Spanish",
  "Hindi",
  "French",
  "Standard Arabic",
  "Bengali",
  "Russian",
  "Portuguese",
  "Urdu",
  "Indonesian",
  "German",
  "Japanese",
  "Swahili",
  "Marathi",
  "Telugu",
  "Turkish",
  "Tamil",
  "Vietnamese",
  "Korean",
] as const;

export const genreList = [
  "Fiction",
  "Mystery",
  "Thriller",
  "Romance",
  "Science Fiction",
  "Fantasy",
  "Historical Fiction",
  "Horror",
  "Crime",
  "Adventure",
  "Young Adult",
  "Non-fiction",
  "Biography/Autobiography",
  "Memoir",
  "Self-help",
  "Business/Finance",
  "Science/Technology",
  "Travel",
  "Poetry",
  "Graphic Novel/Comic",
] as const;
